/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject4 from '../model/InlineObject4';
import InlineObject5 from '../model/InlineObject5';
import InlineObject6 from '../model/InlineObject6';
import InlineResponse200 from '../model/InlineResponse200';
import InlineResponse2001 from '../model/InlineResponse2001';
import InlineResponse2002 from '../model/InlineResponse2002';
import InlineResponse2003 from '../model/InlineResponse2003';
import InlineResponse2004 from '../model/InlineResponse2004';
import InlineResponse2005 from '../model/InlineResponse2005';
import InlineResponse2006 from '../model/InlineResponse2006';
import InlineResponse400 from '../model/InlineResponse400';

/**
* CreateAndManageSubscriptions service.
* @module api/CreateAndManageSubscriptionsApi
* @version 1.0
*/
export default class CreateAndManageSubscriptionsApi {

    /**
    * Constructs a new CreateAndManageSubscriptionsApi. 
    * @alias module:api/CreateAndManageSubscriptionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the cancelSubscription operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~cancelSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel Subscription
     * Cancel a subscription indefinitely. There is no option to restore a canceled subscription. When a subscription is canceled, no more bills will be generated even if the cancellation happens in the middle of a cycle. If you would like to charge one final bill or prorate the amount of the final bill, the One-Time Payment endpoint may be used to process a standalone payment.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject4} opts.inlineObject4 
     * @param {module:api/CreateAndManageSubscriptionsApi~cancelSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2004}
     */
    cancelSubscription(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject4'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling cancelSubscription");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling cancelSubscription");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2004;
      return this.apiClient.callApi(
        '/subscription/cancel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the chargePaymentMethod operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~chargePaymentMethodCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * One-Time Payment
     * Manually process a single transaction independently from a subscription. Using this endpoint will not count toward a subscription payment.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject3} opts.inlineObject3 
     * @param {module:api/CreateAndManageSubscriptionsApi~chargePaymentMethodCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    chargePaymentMethod(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject3'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling chargePaymentMethod");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling chargePaymentMethod");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2003;
      return this.apiClient.callApi(
        '/chargepaymentmethod', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createSubscription operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~createSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Subscription
     * Create a weekly, biweekly, or monthly subscription with a fixed payment amount. If the frequency is set to Monthly, the BillingDate will determine which day of the month the subsequent charges will occur. Weekly and biweekly charges will occur on the same day of the week as the initial payment
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject1} opts.inlineObject1 
     * @param {module:api/CreateAndManageSubscriptionsApi~createSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2001}
     */
    createSubscription(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject1'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling createSubscription");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling createSubscription");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;
      return this.apiClient.callApi(
        '/subscription', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubscriptionById operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~getSubscriptionByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2005} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lookup Subscription
     * Retrieve subscription data including all bills using the Subscription ID.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject5} opts.inlineObject5 
     * @param {module:api/CreateAndManageSubscriptionsApi~getSubscriptionByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2005}
     */
    getSubscriptionById(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject5'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling getSubscriptionById");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling getSubscriptionById");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2005;
      return this.apiClient.callApi(
        '/subscription/list', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the pauseResume operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~pauseResumeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2006} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pause/Resume Subscription
     * Either pause an active subscription by passing the boolean value true in the Paused field, which prevents any new payments from being charged, or resume a subscription by passing the boolean value false in the Paused field and recalculate the billing date for the end of the next cycle. When a subscription is paused, no new charges will occur until the subscription is resumed. The amount of the next payment after the subscription resumes will not be changed.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject6} opts.inlineObject6 
     * @param {module:api/CreateAndManageSubscriptionsApi~pauseResumeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2006}
     */
    pauseResume(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject6'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling pauseResume");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling pauseResume");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2006;
      return this.apiClient.callApi(
        '/subscription/pause', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the payBill operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~payBillCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pay Subscription Bill
     * Manually pay a bill that's part of a subscription prior to the due date or past the due date if the automatic payment fails. Using this endpoint to pay a bill will count toward a subscription payment.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject2} opts.inlineObject2 
     * @param {module:api/CreateAndManageSubscriptionsApi~payBillCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    payBill(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject2'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling payBill");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling payBill");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/paybill', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSubscription operation.
     * @callback module:api/CreateAndManageSubscriptionsApi~updateSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Subscription
     * Update data related to a subscription.
     * @param {String} ePIId Merchant's unique 4-part key, which is provided after boarding with the processor
     * @param {String} ePISignature HMAC of the endpoint and payload
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject} opts.inlineObject 
     * @param {module:api/CreateAndManageSubscriptionsApi~updateSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse200}
     */
    updateSubscription(ePIId, ePISignature, opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject'];
      // verify the required parameter 'ePIId' is set
      if (ePIId === undefined || ePIId === null) {
        throw new Error("Missing the required parameter 'ePIId' when calling updateSubscription");
      }
      // verify the required parameter 'ePISignature' is set
      if (ePISignature === undefined || ePISignature === null) {
        throw new Error("Missing the required parameter 'ePISignature' when calling updateSubscription");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'EPI-Id': ePIId,
        'EPI-Signature': ePISignature
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;
      return this.apiClient.callApi(
        '/subscription', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
