-- 043_product_catalog: the company's full product list with active ingredients,
-- as shown on the technicians' service reports. Re-runnable: existing products
-- (matched case-insensitively by name) keep their EPA number and default quantity
-- and only gain the active ingredient.
ALTER TABLE products ADD COLUMN IF NOT EXISTS active_ingredient TEXT;

INSERT INTO products (name, unit, active_ingredient) VALUES
  ('565 Plus', 'oz', 'Pyrethrins 0.5%; Piperonyl Butoxide 1.0%; n-Octyl Bicycloheptene Dicarboximide 1.0%'),
  ('Advion Ant Gel', 'oz', 'Indoxacarb 0.05%'),
  ('Advion Fire Ant Bait', 'lb', NULL),
  ('Advion Insect Granular', 'lb', 'Indoxacarb 0.22%'),
  ('Advion WDG', 'oz', 'Indoxacarb 20%'),
  ('Alpine WSG', 'oz', 'Dinotefuran 40%'),
  ('Altosid Pro G', 'lb', 'Methoprene 1.5%'),
  ('American Brand Granules', 'lb', 'Permethrin 0.25%'),
  ('Archer IGR', 'oz', 'Pyriproxyfen 1.3%'),
  ('Bifen I/T', 'oz', 'Bifenthrin 7.9%'),
  ('Bifen L/P', 'lb', 'Bifenthrin 0.2%'),
  ('Bora Care', 'oz', 'Disodium Octaborate Tetrahydrate 40%'),
  ('Contrac Blox', 'oz', 'Bromadiolone 0.005%'),
  ('Cross Check Plus', 'oz', 'Bifenthrin 7.9%'),
  ('Cy-Kick CS', 'oz', 'Cyfluthrin 6%'),
  ('Cyper TC', 'oz', 'Cypermethrin 25.4%'),
  ('Cyzmic CS', 'oz', 'Lambda-cyhalothrin 9.7%'),
  ('D-Fense Dust', 'oz', 'Deltamethrin'),
  ('D-Fense SC', 'oz', 'Deltamethrin 4.75%'),
  ('Delta Dust', 'oz', 'Deltamethrin 0.05%'),
  ('Demand CS', 'oz', 'Lambda-Cyhalothrin 9.7%'),
  ('First Strike', 'oz', 'Difethialone 0.0025%'),
  ('IN2MIX', 'oz', 'Pyriproxyfen 75%'),
  ('Niban', 'lb', 'Orthoboric Acid 5%'),
  ('Nyguard IGR', 'oz', 'Pyridine 10%'),
  ('One Guard', 'oz', 'Lambda-Cyhalothrin 4%; Prallethrin 0.4%; Pyriproxyfen 1.3%; Piperonyl Butoxide 6%'),
  ('Onslaught', 'oz', 'Benzeneacetate 6.4%'),
  ('Onslaught FastCap', 'oz', 'Esfenvalerate 6.40%'),
  ('Optiguard', 'oz', 'Thiamethoxam 0.01%'),
  ('Phantom', 'oz', 'Chlorfenapyr 31.45%'),
  ('Phantom RTS', 'oz', 'Chlorfenapyr 0.5%'),
  ('Premise Foam', 'oz', 'Imidacloprid 0.05%'),
  ('Ridesco WG', 'oz', 'Dinotefuran 20%'),
  ('Scion', 'oz', 'Gamma-cyhalothrin 5.9%'),
  ('Sector', 'oz', 'Permethrin 10%; Piperonyl Butoxide 10%'),
  ('Sentricon: Recruit AG', 'ea', 'Noviflumuron 0.5%'),
  ('Sentricon: Recruit HD', 'ea', 'Noviflumuron 0.5%'),
  ('Silverfish Paks', 'ea', 'Boric Acid 20%'),
  ('Snake a Way', 'lb', 'Naphthalene 7%; Sulfur 28%'),
  ('Sumilarv', 'oz', 'Pyridine 0.5%'),
  ('Suspend SC', 'oz', 'Deltamethrin 4.75%'),
  ('Talon G', 'lb', 'Benzopyran 0.005%'),
  ('Talstar P', 'oz', 'Bifenthrin 7.9%'),
  ('Tandem', 'oz', 'Thiamethoxam 11.6%'),
  ('Taurus SC (Termiticide)', 'oz', 'Fipronil 9.1%'),
  ('Tempo Dust', 'oz', 'Cyfluthrin 1.0%'),
  ('Tempo SC', 'oz', 'Cyfluthrin, Cyano 11.8%'),
  ('Temprid FX', 'oz', 'Imidacloprid 21.0%; Cyfluthrin 10.5%'),
  ('Termidor HE', 'oz', 'Fipronil 8.73%'),
  ('Termidor SC', 'oz', 'Fipronil 9.1%'),
  ('Top Choice', 'lb', 'Fipronil 0.0143%'),
  ('Transport Mikron', 'oz', NULL),
  ('Trelona ATBS', 'ea', 'Novaluron 0.50%'),
  ('Ultracide', 'oz', 'Pyriproxyfen 0.1%; Pyrethrins 0.05%; n-Octyl Bicycloheptene Dicarboximide 0.40%; Permethrin 0.40%; Related Compounds 0.035%'),
  ('Wasp Freeze', 'oz', 'd-trans Allethrin 0.129%; Phenothrin 0.12%'),
  ('Zenprox', 'oz', 'Etofenprox 16.2%; Piperonyl Butoxide 64.8%')
ON CONFLICT (lower(name)) DO UPDATE SET
  active_ingredient = COALESCE(EXCLUDED.active_ingredient, products.active_ingredient),
  updated_at = now();
