/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankAccountDataAllOf from './BankAccountDataAllOf';

/**
 * The BankAccountData model module.
 * @module model/BankAccountData
 * @version 1.0
 */
class BankAccountData {
    /**
     * Constructs a new <code>BankAccountData</code>.
     * Data related to a customer&#39;s bank account
     * @alias module:model/BankAccountData
     * @extends module:model/BankAccountDataAllOf
     * @implements module:model/BankAccountDataAllOf
     * @param accountNumber {String} The account number to be acted upon during the transaction
     * @param routingNumber {String} The bank routing number associated with the account number for an ACH transaction
     * @param firstName {String} The account holder's first name
     * @param lastName {String} The account holder's last name
     * @param bankAccountType {module:model/BankAccountData.BankAccountTypeEnum} Bank account type
     */
    constructor(accountNumber, routingNumber, firstName, lastName, bankAccountType) { 
        BankAccountDataAllOf.initialize(this);
        BankAccountData.initialize(this, accountNumber, routingNumber, firstName, lastName, bankAccountType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountNumber, routingNumber, firstName, lastName, bankAccountType) { 
    }

    /**
     * Constructs a <code>BankAccountData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankAccountData} obj Optional instance to populate.
     * @return {module:model/BankAccountData} The populated <code>BankAccountData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankAccountData();
            BankAccountDataAllOf.constructFromObject(data, obj);
            BankAccountDataAllOf.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement BankAccountDataAllOf interface:
/**
 * The account number to be acted upon during the transaction
 * @member {String} AccountNumber
 */
BankAccountDataAllOf.prototype['AccountNumber'] = undefined;
/**
 * The bank routing number associated with the account number for an ACH transaction
 * @member {String} RoutingNumber
 */
BankAccountDataAllOf.prototype['RoutingNumber'] = undefined;
/**
 * The account holder's first name
 * @member {String} FirstName
 */
BankAccountDataAllOf.prototype['FirstName'] = undefined;
/**
 * The account holder's last name
 * @member {String} LastName
 */
BankAccountDataAllOf.prototype['LastName'] = undefined;
/**
 * Bank account type
 * @member {module:model/BankAccountDataAllOf.BankAccountTypeEnum} BankAccountType
 */
BankAccountDataAllOf.prototype['BankAccountType'] = undefined;




export default BankAccountData;

