/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BankAccountDataAllOf model module.
 * @module model/BankAccountDataAllOf
 * @version 1.0
 */
class BankAccountDataAllOf {
    /**
     * Constructs a new <code>BankAccountDataAllOf</code>.
     * @alias module:model/BankAccountDataAllOf
     */
    constructor() { 
        
        BankAccountDataAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BankAccountDataAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankAccountDataAllOf} obj Optional instance to populate.
     * @return {module:model/BankAccountDataAllOf} The populated <code>BankAccountDataAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankAccountDataAllOf();

            if (data.hasOwnProperty('AccountNumber')) {
                obj['AccountNumber'] = ApiClient.convertToType(data['AccountNumber'], 'String');
            }
            if (data.hasOwnProperty('RoutingNumber')) {
                obj['RoutingNumber'] = ApiClient.convertToType(data['RoutingNumber'], 'String');
            }
            if (data.hasOwnProperty('FirstName')) {
                obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
            }
            if (data.hasOwnProperty('LastName')) {
                obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
            }
            if (data.hasOwnProperty('BankAccountType')) {
                obj['BankAccountType'] = ApiClient.convertToType(data['BankAccountType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The account number to be acted upon during the transaction
 * @member {String} AccountNumber
 */
BankAccountDataAllOf.prototype['AccountNumber'] = undefined;

/**
 * The bank routing number associated with the account number for an ACH transaction
 * @member {String} RoutingNumber
 */
BankAccountDataAllOf.prototype['RoutingNumber'] = undefined;

/**
 * The account holder's first name
 * @member {String} FirstName
 */
BankAccountDataAllOf.prototype['FirstName'] = undefined;

/**
 * The account holder's last name
 * @member {String} LastName
 */
BankAccountDataAllOf.prototype['LastName'] = undefined;

/**
 * Bank account type
 * @member {module:model/BankAccountDataAllOf.BankAccountTypeEnum} BankAccountType
 */
BankAccountDataAllOf.prototype['BankAccountType'] = undefined;





/**
 * Allowed values for the <code>BankAccountType</code> property.
 * @enum {String}
 * @readonly
 */
BankAccountDataAllOf['BankAccountTypeEnum'] = {

    /**
     * value: "Checking"
     * @const
     */
    "Checking": "Checking",

    /**
     * value: "Savings"
     * @const
     */
    "Savings": "Savings"
};



export default BankAccountDataAllOf;

