/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditCardDataAllOf model module.
 * @module model/CreditCardDataAllOf
 * @version 1.0
 */
class CreditCardDataAllOf {
    /**
     * Constructs a new <code>CreditCardDataAllOf</code>.
     * @alias module:model/CreditCardDataAllOf
     */
    constructor() { 
        
        CreditCardDataAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditCardDataAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditCardDataAllOf} obj Optional instance to populate.
     * @return {module:model/CreditCardDataAllOf} The populated <code>CreditCardDataAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditCardDataAllOf();

            if (data.hasOwnProperty('AccountNumber')) {
                obj['AccountNumber'] = ApiClient.convertToType(data['AccountNumber'], 'String');
            }
            if (data.hasOwnProperty('ExpirationDate')) {
                obj['ExpirationDate'] = ApiClient.convertToType(data['ExpirationDate'], 'String');
            }
            if (data.hasOwnProperty('CVV')) {
                obj['CVV'] = ApiClient.convertToType(data['CVV'], 'String');
            }
            if (data.hasOwnProperty('FirstName')) {
                obj['FirstName'] = ApiClient.convertToType(data['FirstName'], 'String');
            }
            if (data.hasOwnProperty('LastName')) {
                obj['LastName'] = ApiClient.convertToType(data['LastName'], 'String');
            }
            if (data.hasOwnProperty('PostalCode')) {
                obj['PostalCode'] = ApiClient.convertToType(data['PostalCode'], 'String');
            }
            if (data.hasOwnProperty('StreetAddress')) {
                obj['StreetAddress'] = ApiClient.convertToType(data['StreetAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Credit card number
 * @member {String} AccountNumber
 */
CreditCardDataAllOf.prototype['AccountNumber'] = undefined;

/**
 * Credit card’s expiration date in YYMM format
 * @member {String} ExpirationDate
 */
CreditCardDataAllOf.prototype['ExpirationDate'] = undefined;

/**
 * Credit card’s CVV2 number
 * @member {String} CVV
 */
CreditCardDataAllOf.prototype['CVV'] = undefined;

/**
 * The cardholder's first name
 * @member {String} FirstName
 */
CreditCardDataAllOf.prototype['FirstName'] = undefined;

/**
 * The cardholder's last name
 * @member {String} LastName
 */
CreditCardDataAllOf.prototype['LastName'] = undefined;

/**
 * The cardholder's zip code. This field is not required. The PostalCode and StreetAddress fields are part of credit card address verification. These values will be validated against the value recorded at the issuing bank for the account when doing a credit card authorization. The response for this verification is found in the AVSResult field
 * @member {String} PostalCode
 */
CreditCardDataAllOf.prototype['PostalCode'] = undefined;

/**
 * The cardholder's street address. The StreetAddress and PostalCode fields are part of credit card address verification. These values will be validated against the value recorded at the issuing bank for the account when doing a credit card authorization. The response for this verification is found in the AVSResult field
 * @member {String} StreetAddress
 */
CreditCardDataAllOf.prototype['StreetAddress'] = undefined;






export default CreditCardDataAllOf;

