/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomerDataAllOf from './CustomerDataAllOf';

/**
 * The CustomerData model module.
 * @module model/CustomerData
 * @version 1.0
 */
class CustomerData {
    /**
     * Constructs a new <code>CustomerData</code>.
     * Data related to a customer
     * @alias module:model/CustomerData
     * @extends module:model/CustomerDataAllOf
     * @implements module:model/CustomerDataAllOf
     */
    constructor() { 
        CustomerDataAllOf.initialize(this);
        CustomerData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerData} obj Optional instance to populate.
     * @return {module:model/CustomerData} The populated <code>CustomerData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerData();
            CustomerDataAllOf.constructFromObject(data, obj);
            CustomerDataAllOf.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement CustomerDataAllOf interface:
/**
 * Cardholder's first name
 * @member {String} FirstName
 */
CustomerDataAllOf.prototype['FirstName'] = undefined;
/**
 * Cardholder's last name
 * @member {String} LastName
 */
CustomerDataAllOf.prototype['LastName'] = undefined;
/**
 * Cardholder's phone number
 * @member {String} Phone
 */
CustomerDataAllOf.prototype['Phone'] = undefined;
/**
 * Cardholder's email address
 * @member {String} Email
 */
CustomerDataAllOf.prototype['Email'] = undefined;




export default CustomerData;

