/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2003 model module.
 * @module model/InlineResponse2003
 * @version 1.0
 */
class InlineResponse2003 {
    /**
     * Constructs a new <code>InlineResponse2003</code>.
     * Success response
     * @alias module:model/InlineResponse2003
     * @param _date {String} The date of a transaction
     * @param GUID {String} Token/unique transaction ID generated for each financial transaction
     * @param amount {Number} Positive dollar amount of funds to be charged. Decimal point required
     * @param code {String} Contains the Response Code for the transaction requested and should be used to determine the result of the transaction. This information is passed from the issuing bank. The code 00 is returned on Approval, and most other codes indicate a Decline or Error. Please view a full list of Response Codes
     * @param text {String} Contains additional information for the transaction requested. This information can change at any time and should not be used in code to validate the response of a transaction (except for a limited case with Account Updater, for MasterCard only). The field is used to provide more information about the transaction when there is a decline, or a transaction with insufficient information to process
     * @param successful {Boolean} Indicates whether the transaction was successful or not
     */
    constructor(_date, GUID, amount, code, text, successful) { 
        
        InlineResponse2003.initialize(this, _date, GUID, amount, code, text, successful);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _date, GUID, amount, code, text, successful) { 
        obj['Date'] = _date;
        obj['GUID'] = GUID;
        obj['Amount'] = amount;
        obj['Code'] = code;
        obj['Text'] = text;
        obj['Successful'] = successful;
    }

    /**
     * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2003} obj Optional instance to populate.
     * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003();

            if (data.hasOwnProperty('Date')) {
                obj['Date'] = ApiClient.convertToType(data['Date'], 'String');
            }
            if (data.hasOwnProperty('GUID')) {
                obj['GUID'] = ApiClient.convertToType(data['GUID'], 'String');
            }
            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
            }
            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
            if (data.hasOwnProperty('Text')) {
                obj['Text'] = ApiClient.convertToType(data['Text'], 'String');
            }
            if (data.hasOwnProperty('Approval')) {
                obj['Approval'] = ApiClient.convertToType(data['Approval'], 'String');
            }
            if (data.hasOwnProperty('Successful')) {
                obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The date of a transaction
 * @member {String} Date
 */
InlineResponse2003.prototype['Date'] = undefined;

/**
 * Token/unique transaction ID generated for each financial transaction
 * @member {String} GUID
 */
InlineResponse2003.prototype['GUID'] = undefined;

/**
 * Positive dollar amount of funds to be charged. Decimal point required
 * @member {Number} Amount
 */
InlineResponse2003.prototype['Amount'] = undefined;

/**
 * Contains the Response Code for the transaction requested and should be used to determine the result of the transaction. This information is passed from the issuing bank. The code 00 is returned on Approval, and most other codes indicate a Decline or Error. Please view a full list of Response Codes
 * @member {String} Code
 */
InlineResponse2003.prototype['Code'] = undefined;

/**
 * Contains additional information for the transaction requested. This information can change at any time and should not be used in code to validate the response of a transaction (except for a limited case with Account Updater, for MasterCard only). The field is used to provide more information about the transaction when there is a decline, or a transaction with insufficient information to process
 * @member {String} Text
 */
InlineResponse2003.prototype['Text'] = undefined;

/**
 * Contains the approval code for the transaction requested. In the event that there is no approval, this field will be empty. Some issuers will return an authorization code on declined transactions. Use the AUTH_RESP value to determine if a transaction was approved
 * @member {String} Approval
 */
InlineResponse2003.prototype['Approval'] = undefined;

/**
 * Indicates whether the transaction was successful or not
 * @member {Boolean} Successful
 */
InlineResponse2003.prototype['Successful'] = undefined;






export default InlineResponse2003;

