/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001VerifyResult model module.
 * @module model/InlineResponse2001VerifyResult
 * @version 1.0
 */
class InlineResponse2001VerifyResult {
    /**
     * Constructs a new <code>InlineResponse2001VerifyResult</code>.
     * @alias module:model/InlineResponse2001VerifyResult
     */
    constructor() { 
        
        InlineResponse2001VerifyResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001VerifyResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001VerifyResult} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001VerifyResult} The populated <code>InlineResponse2001VerifyResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001VerifyResult();

            if (data.hasOwnProperty('AVSResult')) {
                obj['AVSResult'] = ApiClient.convertToType(data['AVSResult'], 'String');
            }
            if (data.hasOwnProperty('CVResult')) {
                obj['CVResult'] = ApiClient.convertToType(data['CVResult'], 'String');
            }
            if (data.hasOwnProperty('Code')) {
                obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
            }
            if (data.hasOwnProperty('Text')) {
                obj['Text'] = ApiClient.convertToType(data['Text'], 'String');
            }
            if (data.hasOwnProperty('GUID')) {
                obj['GUID'] = ApiClient.convertToType(data['GUID'], 'String');
            }
            if (data.hasOwnProperty('Successful')) {
                obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
            }
            if (data.hasOwnProperty('Date')) {
                obj['Date'] = ApiClient.convertToType(data['Date'], 'String');
            }
            if (data.hasOwnProperty('Approval')) {
                obj['Approval'] = ApiClient.convertToType(data['Approval'], 'String');
            }
            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Address Verification System response for the transaction requested. The address information sent with the transaction is validated against the information at the issuing bank. This is a bank response that is passed on by the EPX processor. EPX supports all AVS formats supported by the card networks.  - A—Address matches, ZIP code does not. Acquirer rights not implied - B—Street addresses match. Postal code not verified due to incompatible formats. (Acquirer sent both street address and postal code) - C—Street address and postal code not verified due to incompatible formats. (Acquirer sent both street address and postal code) - D—Street addresses and postal codes match - F—Street address and postal code match. Applies to U.K. only - G—Address information not verified for international transaction. Issuer is not an AVS participant, or AVS data was present in the request but issuer did not return an AVS result, or Visa performed AVS on behalf of the issuer and there was no address record on file for this account. - I—Address information not verified - M—Street address and postal code match - N—No match. Acquirer sent postal/ZIP code only, or street address only, or both postal code and street address - P—Postal code match. Acquirer sent both postal code and street address, but street address not verified due to incompatible formats - U—Address not verified for domestic transaction. Issuer is not an AVS participant, or AVS data was present in the request but issuer did not return an AVS result, or Visa performed AVS on behalf of the issuer and there was no address record on file for this account - W—Not applicable. If present, replaced with “Z” by V.I.P. Available for U.S. issuers only - X—Not applicable. If present, replaced with “Y” by V.I.P. Available for U.S. issuers only - Y—Street address and postal code match - Z—Postal/ZIP matches; street address does not match
 * @member {String} AVSResult
 */
InlineResponse2001VerifyResult.prototype['AVSResult'] = undefined;

/**
 * The CVV value sent with the transaction is validated against the information at the issuing bank. This is a bank response that is passed on by EPX. - Space—No result - M—CVV2 match - N—CVV2 does not match - P—Not processed - S—CVV2 should be on the card, but the merchant indicates that it is not - U—Issue is not certified or has not provided Visa with encryption keys, or both
 * @member {String} CVResult
 */
InlineResponse2001VerifyResult.prototype['CVResult'] = undefined;

/**
 * Contains the Response Code for the transaction requested and should be used to determine the result of the transaction. This information is passed from the issuing bank. The code 00 is returned on Approval, and most other codes indicate a Decline or Error. Please view a full list of Response Codes
 * @member {String} Code
 */
InlineResponse2001VerifyResult.prototype['Code'] = undefined;

/**
 * Contains additional information for the transaction requested. This information can change at any time and should not be used in code to validate the response of a transaction (except for a limited case with Account Updater, for MasterCard only). The field is used to provide more information about the transaction when there is a decline, or a transaction with insufficient information to process
 * @member {String} Text
 */
InlineResponse2001VerifyResult.prototype['Text'] = undefined;

/**
 * Token/unique transaction ID generated for each financial transaction
 * @member {String} GUID
 */
InlineResponse2001VerifyResult.prototype['GUID'] = undefined;

/**
 * Indicates whether the transaction was successful or not
 * @member {Boolean} Successful
 */
InlineResponse2001VerifyResult.prototype['Successful'] = undefined;

/**
 * The date and time of a transaction
 * @member {String} Date
 */
InlineResponse2001VerifyResult.prototype['Date'] = undefined;

/**
 * Contains the approval code for the transaction requested. In the event that there is no approval, this field will be empty. Some issuers will return an authorization code on declined transactions. Use the AUTH_RESP value to determine if a transaction was approved
 * @member {String} Approval
 */
InlineResponse2001VerifyResult.prototype['Approval'] = undefined;

/**
 * The amount submitted with this transaction
 * @member {String} Amount
 */
InlineResponse2001VerifyResult.prototype['Amount'] = undefined;






export default InlineResponse2001VerifyResult;

