/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2005Customer from './InlineResponse2005Customer';
import InlineResponse2005PaymentMethod from './InlineResponse2005PaymentMethod';
import InlineResponse2005Payments from './InlineResponse2005Payments';

/**
 * The InlineResponse2005Bills model module.
 * @module model/InlineResponse2005Bills
 * @version 1.0
 */
class InlineResponse2005Bills {
    /**
     * Constructs a new <code>InlineResponse2005Bills</code>.
     * @alias module:model/InlineResponse2005Bills
     */
    constructor() { 
        
        InlineResponse2005Bills.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2005Bills</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2005Bills} obj Optional instance to populate.
     * @return {module:model/InlineResponse2005Bills} The populated <code>InlineResponse2005Bills</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2005Bills();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('DueDate')) {
                obj['DueDate'] = ApiClient.convertToType(data['DueDate'], 'String');
            }
            if (data.hasOwnProperty('Paid')) {
                obj['Paid'] = ApiClient.convertToType(data['Paid'], 'Boolean');
            }
            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
            }
            if (data.hasOwnProperty('Status')) {
                obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
            }
            if (data.hasOwnProperty('Active')) {
                obj['Active'] = ApiClient.convertToType(data['Active'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'Number');
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [InlineResponse2005Payments]);
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = InlineResponse2005Customer.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = InlineResponse2005PaymentMethod.constructFromObject(data['paymentMethod']);
            }
        }
        return obj;
    }


}

/**
 * ID number
 * @member {Number} id
 */
InlineResponse2005Bills.prototype['id'] = undefined;

/**
 * The date that the next bill is due
 * @member {String} DueDate
 */
InlineResponse2005Bills.prototype['DueDate'] = undefined;

/**
 * A boolean value indicating whether the bill has been paid
 * @member {module:model/InlineResponse2005Bills.PaidEnum} Paid
 */
InlineResponse2005Bills.prototype['Paid'] = undefined;

/**
 * Positive dollar amount of funds to be charged every cycle (weekly, biweekly, monthly). Decimal point required
 * @member {Number} Amount
 */
InlineResponse2005Bills.prototype['Amount'] = undefined;

/**
 * Subscription Status can be Active, Paused, or Expired
 * @member {module:model/InlineResponse2005Bills.StatusEnum} Status
 */
InlineResponse2005Bills.prototype['Status'] = undefined;

/**
 * Indicates whether the subscription is Active
 * @member {Boolean} Active
 */
InlineResponse2005Bills.prototype['Active'] = undefined;

/**
 * Timestamp when the subscription was created
 * @member {String} createdAt
 */
InlineResponse2005Bills.prototype['createdAt'] = undefined;

/**
 * Timestamp when the subscription was last updated
 * @member {String} updatedAt
 */
InlineResponse2005Bills.prototype['updatedAt'] = undefined;

/**
 * Subscription ID number
 * @member {Number} subscriptionId
 */
InlineResponse2005Bills.prototype['subscriptionId'] = undefined;

/**
 * Array of payment data
 * @member {Array.<module:model/InlineResponse2005Payments>} payments
 */
InlineResponse2005Bills.prototype['payments'] = undefined;

/**
 * @member {module:model/InlineResponse2005Customer} customer
 */
InlineResponse2005Bills.prototype['customer'] = undefined;

/**
 * @member {module:model/InlineResponse2005PaymentMethod} paymentMethod
 */
InlineResponse2005Bills.prototype['paymentMethod'] = undefined;





/**
 * Allowed values for the <code>Paid</code> property.
 * @enum {Boolean}
 * @readonly
 */
InlineResponse2005Bills['PaidEnum'] = {

    /**
     * value: "true"
     * @const
     */
    "true": "true",

    /**
     * value: "false"
     * @const
     */
    "false": "false"
};


/**
 * Allowed values for the <code>Status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2005Bills['StatusEnum'] = {

    /**
     * value: "Active"
     * @const
     */
    "Active": "Active",

    /**
     * value: "Paused"
     * @const
     */
    "Paused": "Paused",

    /**
     * value: "Expired"
     * @const
     */
    "Expired": "Expired",

    /**
     * value: "Canceled"
     * @const
     */
    "Canceled": "Canceled"
};



export default InlineResponse2005Bills;

