/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2001VerifyResult from './InlineResponse2001VerifyResult';

/**
 * The InlineResponse2001 model module.
 * @module model/InlineResponse2001
 * @version 1.0
 */
class InlineResponse2001 {
    /**
     * Constructs a new <code>InlineResponse2001</code>.
     * Success response
     * @alias module:model/InlineResponse2001
     */
    constructor() { 
        
        InlineResponse2001.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
            }
            if (data.hasOwnProperty('Frequency')) {
                obj['Frequency'] = ApiClient.convertToType(data['Frequency'], 'String');
            }
            if (data.hasOwnProperty('BillingDate')) {
                obj['BillingDate'] = ApiClient.convertToType(data['BillingDate'], 'Date');
            }
            if (data.hasOwnProperty('FailureOption')) {
                obj['FailureOption'] = ApiClient.convertToType(data['FailureOption'], 'String');
            }
            if (data.hasOwnProperty('NumberOfPayments')) {
                obj['NumberOfPayments'] = ApiClient.convertToType(data['NumberOfPayments'], 'Number');
            }
            if (data.hasOwnProperty('Retries')) {
                obj['Retries'] = ApiClient.convertToType(data['Retries'], 'Number');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('Status')) {
                obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
            }
            if (data.hasOwnProperty('PaymentsRemaining')) {
                obj['PaymentsRemaining'] = ApiClient.convertToType(data['PaymentsRemaining'], 'Number');
            }
            if (data.hasOwnProperty('customerId')) {
                obj['customerId'] = ApiClient.convertToType(data['customerId'], 'Number');
            }
            if (data.hasOwnProperty('paymentmethodId')) {
                obj['paymentmethodId'] = ApiClient.convertToType(data['paymentmethodId'], 'Number');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('VerifyResult')) {
                obj['VerifyResult'] = InlineResponse2001VerifyResult.constructFromObject(data['VerifyResult']);
            }
        }
        return obj;
    }


}

/**
 * ID number
 * @member {Number} id
 */
InlineResponse2001.prototype['id'] = undefined;

/**
 * Positive dollar amount of funds to be charged every cycle (weekly, biweekly, monthly). Decimal point required
 * @member {Number} Amount
 */
InlineResponse2001.prototype['Amount'] = undefined;

/**
 * Weekly, biweekly, or monthly frequency
 * @member {module:model/InlineResponse2001.FrequencyEnum} Frequency
 */
InlineResponse2001.prototype['Frequency'] = undefined;

/**
 * The date that the first payment will be charged. If the frequency is set to Monthly, this date will also determine which day of the month the subsequent charges will occur. Weekly and biweekly charges will occur on the same day of the week as the initial payment
 * @member {Date} BillingDate
 */
InlineResponse2001.prototype['BillingDate'] = undefined;

/**
 * The action to be performed after a failed transaction or the last failed retry.   - **Forward** - The current balance will be transferred onto the next cycle - **Skip** - The current cycle will be skipped and will resume after the single skipped cycle. The amount of the next payment will not be affected - **Pause** - The subscription will be paused indefinitely. No new charges will occur until the subscription is resumed. The amount of the next payment after the subscription resumes will not be affected 
 * @member {module:model/InlineResponse2001.FailureOptionEnum} FailureOption
 */
InlineResponse2001.prototype['FailureOption'] = undefined;

/**
 * Number of cycles to be charged. If not provided, the subscription will never expire
 * @member {Number} NumberOfPayments
 */
InlineResponse2001.prototype['NumberOfPayments'] = undefined;

/**
 * The number of consecutive days to attempt a payment after a failure. One attempt will be made per day. If the payment still fails on the last attempt, the FailureOption will be enforced. If a value is not provided for Retries, it will be defaulted to 3
 * @member {Number} Retries
 * @default 3
 */
InlineResponse2001.prototype['Retries'] = 3;

/**
 * An optional description field
 * @member {String} Description
 */
InlineResponse2001.prototype['Description'] = undefined;

/**
 * Subscription status can be Active, Paused, or Expired
 * @member {module:model/InlineResponse2001.StatusEnum} Status
 */
InlineResponse2001.prototype['Status'] = undefined;

/**
 * Number of payments that haven't been charged yet
 * @member {Number} PaymentsRemaining
 */
InlineResponse2001.prototype['PaymentsRemaining'] = undefined;

/**
 * customerID
 * @member {Number} customerId
 */
InlineResponse2001.prototype['customerId'] = undefined;

/**
 * paymentmethodId
 * @member {Number} paymentmethodId
 */
InlineResponse2001.prototype['paymentmethodId'] = undefined;

/**
 * Timestamp when the subscription was last updated
 * @member {String} updatedAt
 */
InlineResponse2001.prototype['updatedAt'] = undefined;

/**
 * Timestamp when the subscription was created
 * @member {String} createdAt
 */
InlineResponse2001.prototype['createdAt'] = undefined;

/**
 * @member {module:model/InlineResponse2001VerifyResult} VerifyResult
 */
InlineResponse2001.prototype['VerifyResult'] = undefined;





/**
 * Allowed values for the <code>Frequency</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2001['FrequencyEnum'] = {

    /**
     * value: "Weekly"
     * @const
     */
    "Weekly": "Weekly",

    /**
     * value: "BiWeekly"
     * @const
     */
    "BiWeekly": "BiWeekly",

    /**
     * value: "Monthly"
     * @const
     */
    "Monthly": "Monthly"
};


/**
 * Allowed values for the <code>FailureOption</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2001['FailureOptionEnum'] = {

    /**
     * value: "Forward"
     * @const
     */
    "Forward": "Forward",

    /**
     * value: "Skip"
     * @const
     */
    "Skip": "Skip",

    /**
     * value: "Pause"
     * @const
     */
    "Pause": "Pause"
};


/**
 * Allowed values for the <code>Status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2001['StatusEnum'] = {

    /**
     * value: "Active"
     * @const
     */
    "Active": "Active",

    /**
     * value: "Paused"
     * @const
     */
    "Paused": "Paused",

    /**
     * value: "Expired"
     * @const
     */
    "Expired": "Expired",

    /**
     * value: "Canceled"
     * @const
     */
    "Canceled": "Canceled"
};



export default InlineResponse2001;

