/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankAccountData from './BankAccountData';
import CreditCardData from './CreditCardData';
import PreviousPayment from './PreviousPayment';

/**
 * The SubscriptionPaymentMethod model module.
 * @module model/SubscriptionPaymentMethod
 * @version 1.0
 */
class SubscriptionPaymentMethod {
    /**
     * Constructs a new <code>SubscriptionPaymentMethod</code>.
     * The PaymentMethod object can be created using CreditCardData, BankAccountData, or the token from a previous payment
     * @alias module:model/SubscriptionPaymentMethod
     */
    constructor() { 
        
        SubscriptionPaymentMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriptionPaymentMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionPaymentMethod} obj Optional instance to populate.
     * @return {module:model/SubscriptionPaymentMethod} The populated <code>SubscriptionPaymentMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionPaymentMethod();

            if (data.hasOwnProperty('CreditCardData')) {
                obj['CreditCardData'] = CreditCardData.constructFromObject(data['CreditCardData']);
            }
            if (data.hasOwnProperty('BankAccountData')) {
                obj['BankAccountData'] = BankAccountData.constructFromObject(data['BankAccountData']);
            }
            if (data.hasOwnProperty('PreviousPayment')) {
                obj['PreviousPayment'] = PreviousPayment.constructFromObject(data['PreviousPayment']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CreditCardData} CreditCardData
 */
SubscriptionPaymentMethod.prototype['CreditCardData'] = undefined;

/**
 * @member {module:model/BankAccountData} BankAccountData
 */
SubscriptionPaymentMethod.prototype['BankAccountData'] = undefined;

/**
 * @member {module:model/PreviousPayment} PreviousPayment
 */
SubscriptionPaymentMethod.prototype['PreviousPayment'] = undefined;






export default SubscriptionPaymentMethod;

