/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionSubscriptionData model module.
 * @module model/SubscriptionSubscriptionData
 * @version 1.0
 */
class SubscriptionSubscriptionData {
    /**
     * Constructs a new <code>SubscriptionSubscriptionData</code>.
     * @alias module:model/SubscriptionSubscriptionData
     */
    constructor() { 
        
        SubscriptionSubscriptionData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriptionSubscriptionData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionSubscriptionData} obj Optional instance to populate.
     * @return {module:model/SubscriptionSubscriptionData} The populated <code>SubscriptionSubscriptionData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionSubscriptionData();

            if (data.hasOwnProperty('Amount')) {
                obj['Amount'] = ApiClient.convertToType(data['Amount'], 'Number');
            }
            if (data.hasOwnProperty('Frequency')) {
                obj['Frequency'] = ApiClient.convertToType(data['Frequency'], 'String');
            }
            if (data.hasOwnProperty('FailureOption')) {
                obj['FailureOption'] = ApiClient.convertToType(data['FailureOption'], 'String');
            }
            if (data.hasOwnProperty('NumberOfPayments')) {
                obj['NumberOfPayments'] = ApiClient.convertToType(data['NumberOfPayments'], 'Number');
            }
            if (data.hasOwnProperty('Retries')) {
                obj['Retries'] = ApiClient.convertToType(data['Retries'], 'Number');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Positive dollar amount of funds to be charged every cycle (weekly, biweekly, monthly). Decimal point required
 * @member {Number} Amount
 */
SubscriptionSubscriptionData.prototype['Amount'] = undefined;

/**
 * Weekly, biweekly, or monthly frequency
 * @member {module:model/SubscriptionSubscriptionData.FrequencyEnum} Frequency
 */
SubscriptionSubscriptionData.prototype['Frequency'] = undefined;

/**
 * The action to be performed after a failed transaction or the last failed retry.   - **Forward** - The current balance will be transferred onto the next cycle - **Skip** - The current cycle will be skipped and will resume after the single skipped cycle. The amount of the next payment will not be affected - **Pause** - The subscription will be paused indefinitely. No new charges will occur until the subscription is resumed. The amount of the next payment after the subscription resumes will not be affected 
 * @member {module:model/SubscriptionSubscriptionData.FailureOptionEnum} FailureOption
 */
SubscriptionSubscriptionData.prototype['FailureOption'] = undefined;

/**
 * Number of cycles to be charged. If not provided, the subscription will never expire
 * @member {Number} NumberOfPayments
 */
SubscriptionSubscriptionData.prototype['NumberOfPayments'] = undefined;

/**
 * The number of consecutive days to attempt a payment after a failure. One attempt will be made per day. If the payment still fails on the last attempt, the FailureOption will be enforced. If a value is not provided for Retries, it will be defaulted to 3
 * @member {Number} Retries
 * @default 3
 */
SubscriptionSubscriptionData.prototype['Retries'] = 3;

/**
 * An optional description field
 * @member {String} Description
 */
SubscriptionSubscriptionData.prototype['Description'] = undefined;





/**
 * Allowed values for the <code>Frequency</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionSubscriptionData['FrequencyEnum'] = {

    /**
     * value: "Weekly"
     * @const
     */
    "Weekly": "Weekly",

    /**
     * value: "BiWeekly"
     * @const
     */
    "BiWeekly": "BiWeekly",

    /**
     * value: "Monthly"
     * @const
     */
    "Monthly": "Monthly"
};


/**
 * Allowed values for the <code>FailureOption</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionSubscriptionData['FailureOptionEnum'] = {

    /**
     * value: "Forward"
     * @const
     */
    "Forward": "Forward",

    /**
     * value: "Skip"
     * @const
     */
    "Skip": "Skip",

    /**
     * value: "Pause"
     * @const
     */
    "Pause": "Pause"
};



export default SubscriptionSubscriptionData;

