/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecurringBillingApi);
  }
}(this, function(expect, RecurringBillingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecurringBillingApi.CreditCardDataAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreditCardDataAllOf', function() {
    it('should create an instance of CreditCardDataAllOf', function() {
      // uncomment below and update the code to test CreditCardDataAllOf
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be.a(RecurringBillingApi.CreditCardDataAllOf);
    });

    it('should have the property accountNumber (base name: "AccountNumber")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "ExpirationDate")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property CVV (base name: "CVV")', function() {
      // uncomment below and update the code to test the property CVV
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "FirstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "LastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "PostalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "StreetAddress")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instane = new RecurringBillingApi.CreditCardDataAllOf();
      //expect(instance).to.be();
    });

  });

}));
