/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecurringBillingApi);
  }
}(this, function(expect, RecurringBillingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecurringBillingApi.InlineResponse2005Payments();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2005Payments', function() {
    it('should create an instance of InlineResponse2005Payments', function() {
      // uncomment below and update the code to test InlineResponse2005Payments
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be.a(RecurringBillingApi.InlineResponse2005Payments);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "Date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property GUID (base name: "GUID")', function() {
      // uncomment below and update the code to test the property GUID
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "Amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "Code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "Text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property approval (base name: "Approval")', function() {
      // uncomment below and update the code to test the property approval
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property billId (base name: "billId")', function() {
      // uncomment below and update the code to test the property billId
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

    it('should have the property billerrunId (base name: "billerrunId")', function() {
      // uncomment below and update the code to test the property billerrunId
      //var instane = new RecurringBillingApi.InlineResponse2005Payments();
      //expect(instance).to.be();
    });

  });

}));
