/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecurringBillingApi);
  }
}(this, function(expect, RecurringBillingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecurringBillingApi.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be.a(RecurringBillingApi.InlineResponse2001);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "Amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property frequency (base name: "Frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property billingDate (base name: "BillingDate")', function() {
      // uncomment below and update the code to test the property billingDate
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property failureOption (base name: "FailureOption")', function() {
      // uncomment below and update the code to test the property failureOption
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property numberOfPayments (base name: "NumberOfPayments")', function() {
      // uncomment below and update the code to test the property numberOfPayments
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property retries (base name: "Retries")', function() {
      // uncomment below and update the code to test the property retries
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "Status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property paymentsRemaining (base name: "PaymentsRemaining")', function() {
      // uncomment below and update the code to test the property paymentsRemaining
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property paymentmethodId (base name: "paymentmethodId")', function() {
      // uncomment below and update the code to test the property paymentmethodId
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property verifyResult (base name: "VerifyResult")', function() {
      // uncomment below and update the code to test the property verifyResult
      //var instane = new RecurringBillingApi.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
