/**
 * Recurring Billing API
 * Payments Hub Developers' Recurring Billing API enables you to add recurring payments to your ecommerce website. Whether you need to accept payments each week, every other week, or each month, this API enables you to set the recurring period that works for your business. The subscription will generate a bill for every cycle and automatically charge the payment method on the due date. A bill can be manually paid using the /PayBill endpoint prior to or past the due date if the automatic payment fails. The One-Time Payment endpoint can also be used to accept payments that are independent from a subscription.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RecurringBillingApi);
  }
}(this, function(expect, RecurringBillingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RecurringBillingApi.SubscriptionSubscriptionData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscriptionSubscriptionData', function() {
    it('should create an instance of SubscriptionSubscriptionData', function() {
      // uncomment below and update the code to test SubscriptionSubscriptionData
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be.a(RecurringBillingApi.SubscriptionSubscriptionData);
    });

    it('should have the property amount (base name: "Amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

    it('should have the property frequency (base name: "Frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

    it('should have the property failureOption (base name: "FailureOption")', function() {
      // uncomment below and update the code to test the property failureOption
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

    it('should have the property numberOfPayments (base name: "NumberOfPayments")', function() {
      // uncomment below and update the code to test the property numberOfPayments
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

    it('should have the property retries (base name: "Retries")', function() {
      // uncomment below and update the code to test the property retries
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new RecurringBillingApi.SubscriptionSubscriptionData();
      //expect(instance).to.be();
    });

  });

}));
